metadata.format.version = "1.1"

[versions]

miniplaceholders = "3.0.0-SNAPSHOT"
adventure = "4.24.0"
floodgate = "2.2.4-SNAPSHOT"

[libraries]

miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }

floodgate = { group = "org.geysermc.floodgate", name = "api", version.ref = "floodgate" }

