name: MiniPlaceholders-Floodgate-Expansion
version: '${version}'
author: 4drian3d
main: io.github.miniplaceholders.expansion.floodgate.paper.PaperPlugin
api-version: '1.20'
folia-supported: true
dependencies:
  server:
    MiniPlaceholders:
      required: true
    floodgate:
      required: true